server:
    port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 100200
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #最大空闲时间
      max-idle:
      #最大等待时间，单位ms，超过抛异常
      max-wait-millis: 10000
      #最大连接数
      max-total: 50
      #初始化连接数
      initial-size: 5

#    tomcat:
#      #最大等待连接数量
#      max-idle: 10
#      #最大等待时长，单位ms
#      max-wait: 10000
#      #最大活动连接
#      max-active: 50
#      # 初始化连接数
#      initial-size: 5
mybatis:
  #定义mapper的XML路径
  mapper-locations: classpath:com/example.springboot/mapper/*.xml
  #定义别名扫描的包，需要与@Alias联合使用
  type-aliases-package: com.example.springboot.pojo
  #定义类型转换扫描的包
  type-handlers-package: com.example.springboot.typehandler
logging:
  level:
    root: debug
    org:
      springframework: debug
      org:
        mybatis: debug

