server:
  port: 7001
  servlet:
    context-path: /client02

spring:
  application:
    name: eureka-provider
  mvc:
    view:
      suffix: .jsp
      prefix: /jsp/
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 100200
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #最大空闲时间
      max-idle: 10
      #最大等待时间，单位ms，超过抛异常
      max-wait-millis: 10000
      #最大连接数
      max-total: 50
      #初始化连接数
      initial-size: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatis02.mybatis.pojo
  type-handlers-package: com.example.mybatis02.mybatis.typehandler
  configuration:
    #启用从经典数据库列名A_COLUMN到驼峰式经典Java属性名aColumn的自动映射
    map-underscore-to-camel-case: true
    #控制结果集的提取数量大小
    default-fetch-size: 100
    #设置驱动程序等待数据库响应的秒数
    default-statement-timeout: 30
    #为空值指定JDBC类型
    jdbc-type-for-null: nvarchar
    #指定日志实现 SLF4J | LOG4J | LOG4J2 | JDK_LOGGING | COMMONS_LOGGING | STDOUT_LOGGING | NO_LOGGING
    #log-impl:
    #日志前缀字符
    log-prefix: mybatis
logging:
  config: classpath:logback.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka-server
    register-with-eureka: true #默认true，可不配置
    fetch-registry: true #默认true，可不配置

