server:
  port: 8003

eureka:
  client:
    # 默认拉取服务列表，这里不做配置了
    register-with-eureka: false
    service-url:
      # 服务中心地址
      defaultZone: http://localhost:7000/eureka/,http://localhost:8000/eureka/
#ribbon:
#  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
#  ReadTimeout: 5000    # ribbon read超时时间
#  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
#  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
#  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
#
## 如果同时创建@Configuration Bean，以配置文件的属性为准
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:



# 负载均衡配置为随机策略（product-provider为服务名称，即spring.application.name）
#product-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
