server:
  port: 9999
# 配置应用的名字
spring:
  application:
    name: zuul-server
  redis:
    jedis:
      pool:
        max-active: 5
        min-idle: 100
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 192.168.56.106

eureka:
  client:
    #register-with-eureka: true # 是否将当前应用注册到注册中心， 默认true，这里可以不配置
    #fetch-registry: true # 当前项目是否到注册中心中拉去服务列表，默认true，这里可不一配置
    service-url:
      # 配置服务治理中心
      defaultZone: http://localhost:7000/eureka/,http://localhost:8000/eureka/

# 配置静态路由规则
#zuul:
#  routes:
#    product-provider-v1: /pp/**
#zuul:
#  routes:
#    product-provider: # 自定义节点，用于区分不同的服务
#      path: /pp/** # 服务路径映射规则
#      serviceId: product-provider # 注册中心的服务名
zuul:
  ratelimit:
    enabled: true #开启网关限流
    repository: redis #对应存储类型(用来存储统计信息)
    policy-list:  #限流策略
      #10秒内允许3个访问，并且要求总请求时间小于5秒
      product-provider: #指定针对哪个服务进行限流
        - limit: 3  #在一个单位时间窗口的请求数量
          quota: 5  #在一个单位时间窗口的请求时间限制
          refresh-interval: 10  #单位时间窗口，单位：秒
          type:
            #- user #可指定用户粒度
            - origin #可指定客户端地址粒度
            - url #可指定url粒度

