server:
  port: 7001
spring:
  application:
    # 项目名称/微服务节点名称
    name: product-provider-v1
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 100200
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #最大空闲时间
      max-idle: 10
      #最大等待时间，单位ms，超过抛异常
      max-wait-millis: 10000
      #最大连接数
      max-total: 50
      #初始化连接数
      initial-size: 5
eureka:
  client:
    #是否自动拉去注册中心服务列表，默认true，这里可以不用配置
    fetch-registry: true
    #是否将当前服务注册到注册中心，默认true，这里可以不用配置
    register-with-eureka: true
    service-url:
      # 注册到服务中心
      defaultZone: http://localhost:7000/eureka/,http://localhost:8000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.productprovider.pojo
  #type-handlers-package: com.springcloud.productprovider.typehandler
  configuration:
    #启用从经典数据库列名A_COLUMN到驼峰式经典Java属性名aColumn的自动映射
    map-underscore-to-camel-case: true
    #控制结果集的提取数量大小
    default-fetch-size: 100
    #设置驱动程序等待数据库响应的秒数
    default-statement-timeout: 30
    #为空值指定JDBC类型
    jdbc-type-for-null: nvarchar
    #指定日志实现 SLF4J | LOG4J | LOG4J2 | JDK_LOGGING | COMMONS_LOGGING | STDOUT_LOGGING | NO_LOGGING
    #log-impl:
    #日志前缀字符
    log-prefix: mybatis